info:
  description: Steel Toe and .net POC
  url: https://github.com/KumarShanmugham/config-repo
  applicationSettings:
    connectionstring: "Data Source=steeltoe-demo.database.windows.net;Initial Catalog=School;User Id=appuser;Password=Welcome12345$"
    apikey: 1
    logLevel: error
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.149.83/eureka/
