info:
  description: Steel Toe and .net POC
  url: https://github.com/KumarShanmugham/config-repo
  applicationSettings:
    connectionstring: "Data Source=localhost\\sqlexpress;Initial Catalog=School;Integrated Security=True"
    apikey: 1
    logLevel: error
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
